/**
 * `node scripts/generateFsrsVectors.ts`: write the FSRS-7 test vectors the
 * domain's port is held to (packages/domain/src/fsrs.test.ts), computed
 * with ts-fsrs, pinned in the root package.json. Run it again when the
 * pin moves, and look at what changed: a stored memory was computed with
 * the formulas of its day.
 *
 * Each sequence starts from a new prompt and answers it again and again,
 * at elapsed times from seconds to years, with the memory, the
 * retrievability before the answer and the interval for a few desired
 * retentions after it.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  clipFSRS7Parameters,
  FSRS7_DEFAULT_WEIGHTS,
  FSRS7_MODEL_BOUNDS,
  FSRS7Algorithm,
} from "ts-fsrs/models/fsrs-7";

const OUT = resolve(import.meta.dirname, "../packages/domain/src/testing/fsrsVectors.ts");
const PIN = JSON.parse(readFileSync(resolve(import.meta.dirname, "../package.json"), "utf8")).devDependencies["ts-fsrs"];

/** Deterministic, so a regeneration with the same pin writes the same file. */
function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    let t = (a += 0x6d2b79f5);
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const random = mulberry32(7);
const ELAPSED = [0, 1 / 1440, 10 / 1440, 0.25, 0.75, 1, 1.6, 3, 7.4, 21, 60, 200, 1200];
const RETENTIONS = [0.7, 0.85, 0.9, 0.97];

const parameterSets = [
  [...FSRS7_DEFAULT_WEIGHTS],
  ...[0.15, 0.3].map((spread) =>
    clipFSRS7Parameters(FSRS7_DEFAULT_WEIGHTS.map((w) => w * (1 + spread * (random() * 2 - 1)))),
  ),
];

const sequences = parameterSets.flatMap((w, parameters) => {
  const algorithm = new FSRS7Algorithm(w, FSRS7_MODEL_BOUNDS);
  return Array.from({ length: 12 }, () => {
    let memory: { stability: number; stabilityFast: number; difficulty: number } | null = null;
    const steps = Array.from({ length: 9 }, (_, i) => {
      const rating = 1 + Math.floor(random() * 4);
      const elapsedDays = i === 0 ? 0 : ELAPSED[Math.floor(random() * ELAPSED.length)];
      const retrievability = memory === null ? null : algorithm.curve(elapsedDays, memory).retrievability;
      memory = algorithm.next_state(memory, elapsedDays, rating);
      const intervals = RETENTIONS.map((retention) => algorithm.next_interval(memory!, retention));
      return { rating, elapsedDays, retrievability, memory, intervals };
    });
    return { parameters, steps };
  });
});

const body = `// Generated by scripts/generateFsrsVectors.ts with ts-fsrs ${PIN}. Do not edit.

export const FSRS_VECTOR_RETENTIONS: readonly number[] = ${JSON.stringify(RETENTIONS)};

export const FSRS_VECTOR_PARAMETERS: readonly (readonly number[])[] = ${JSON.stringify(parameterSets)};

export interface FsrsVectorStep {
  rating: 1 | 2 | 3 | 4;
  elapsedDays: number;
  retrievability: number | null;
  memory: { stability: number; stabilityFast: number; difficulty: number };
  intervals: number[];
}

export const FSRS_VECTORS: readonly { parameters: number; steps: FsrsVectorStep[] }[] = ${JSON.stringify(sequences)};
`;
writeFileSync(OUT, body);
console.log(`Wrote ${sequences.length} sequences to ${OUT}.`);
