# File: .github/workflows/publish.yml
name: ci

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js - Cache dependencies - Install dependencies
        uses: ./.github/workflows/setup-node

      - name: Test
        run: npm test

      - name: Build with Next.js
        run: npx next build
        env:
          NEXT_PUBLIC_BASE_PATH: /solid-memo
