name: unpublish
on:
  delete:
    branches:
      - "**"
      - "!gh-pages"
      - "!renovate/**"
    tags:
      - "**"

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  remove-deployment-from-gh-pages:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/gh-pages'

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Unpublish from gh-pages
        env:
          DELETED_REF: ${{ github.event.ref }}
          REF_TYPE: ${{ github.event.ref_type }}
        run: |
          if [[ "${REF_TYPE}" == "branch" ]]; then
            TARGET_PATH="branches/${DELETED_REF#refs/heads/}"
          elif [[ "${REF_TYPE}" == "tag" ]]; then
            TARGET_PATH="tags/${DELETED_REF#refs/tags/}"
          else
            echo "Not a branch or tag, skipping"
            exit 0
          fi

          echo "Target path to remove: $TARGET_PATH"

          git fetch origin gh-pages
          git switch gh-pages

          rm -rf "${TARGET_PATH}"
          git rm -rf --ignore-unmatch "${TARGET_PATH}" || true

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Remove ${TARGET_PATH} after deletion of ${DELETED_REF}"
            git push
          fi
